### ISSUE TITLE
How to file upload redux-bees?

### ISSUE THREAD

**Issue by c0b41** [c0b41/redux-bees#1]
https://github.com/cantierecreativo/redux-bees/issues/19

**Comment by NullVoxPopuli** [comment]
are your files too bug to just convert to a binary string?

**Comment by c0b41** [comment]
@NullVoxPopuli actually this my fork, so that's why open this issue and i'll solve this problem

**Comment by NullVoxPopuli** [comment]
right, but my question still stands? what's the scenario in which you can't just embed the files in your json payload? it works for small files < several MB. (I assume you'd still want multi-part for larger uploads (though, you certainly could send > 20MB json payloads ))

**Comment by c0b41** [comment]
@NullVoxPopuli yeah actually i prefer  to normal file upload for json binary string
